version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  eas:
    image: httpd
    volumes:
      - "${PWD}:/usr/local/apache2/htdocs/"
    environment:
      - VIRTUAL_HOST=cupiditas.local
