spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hr_book
    username: postgres
    password: postgres

server:
 servlet:
  context-path: /hr-book
